// SmartQ Blazor POS
// Copyright (C) 2026 SmartQ (Pty) Ltd
// SPDX-License-Identifier: AGPL-3.0-only
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU Affero General Public License as published by the Free
// Software Foundation, version 3. Commercial licensing is available from
// SmartQ (Pty) Ltd — see LICENSING.md.

using System.Net;
using System.Net.Http.Json;
using System.Text.Json;

namespace Pos.Infrastructure.Sync;

/// <summary>
/// Turns a failed hub response into an exception the caller can act on.
/// </summary>
/// <remarks>
/// Shared by every hub call a terminal makes. It exists as one place because the interesting case is
/// the <c>401</c>: the correct response is to stop, wipe the credential, and ask for re-enrolment
/// rather than to retry against a hub that will never accept this device. A second implementation
/// that forgot that would leave a revoked till retrying forever while claiming to be syncing.
/// </remarks>
internal static class SyncHttpResponse
{
    internal static async Task EnsureSuccessAsync(HttpResponseMessage response, CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(response);

        if (response.IsSuccessStatusCode)
        {
            return;
        }

        if (response.StatusCode == HttpStatusCode.Unauthorized)
        {
            throw new SyncAuthorisationException(
                "The hub rejected this terminal's credential. It may have been revoked.");
        }

        var detail = await response.Content.ReadAsStringAsync(ct).ConfigureAwait(false);
        var summary = detail.Length > 300 ? detail[..300] : detail;

        throw new HttpRequestException(
            $"The hub returned {(int)response.StatusCode} {response.StatusCode}. {summary}",
            inner: null,
            statusCode: response.StatusCode);
    }
}

/// <summary>
/// Rotates this terminal's credential against the hub.
/// </summary>
/// <remarks>
/// <para>
/// Separate from <see cref="ISyncTransport"/> because it is not part of moving records: it is the one
/// call a terminal makes that changes who it is. A rotation that failed must never look like a failed
/// push, or a shop would be told its sales had not synced when they had.
/// </para>
/// <para>
/// The refresh token travels in its own header and never in the body, so it cannot be captured by
/// anything that logs request bodies, and never on an ordinary request, so a secret read out of a
/// proxy log cannot be used to mint a replacement.
/// </para>
/// </remarks>
public sealed class DeviceRotationClient(HttpClient http, SyncEndpoint endpoint)
{
    private static readonly JsonSerializerOptions Json = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        PropertyNameCaseInsensitive = true,
    };

    private readonly HttpClient _http = http ?? throw new ArgumentNullException(nameof(http));
    private readonly SyncEndpoint _endpoint = endpoint ?? throw new ArgumentNullException(nameof(endpoint));

    /// <summary>
    /// Asks the hub to adopt a replacement credential.
    /// </summary>
    /// <param name="refreshToken">The refresh token this device currently holds.</param>
    /// <param name="replacement">The replacement pair, already generated and persisted by the caller.</param>
    /// <param name="ct">Cancellation.</param>
    /// <remarks>
    /// Safe to call twice with the same arguments. That is the whole reason the replacement is
    /// generated by the terminal: a response lost in transit is answered from the hub's stored hashes,
    /// so the retry is recognised as the same rotation rather than mistaken for a stolen token.
    /// </remarks>
    public async Task<DeviceRotateResponse> RotateAsync(
        string refreshToken,
        DeviceCredentialPair replacement,
        CancellationToken ct = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(refreshToken);
        ArgumentNullException.ThrowIfNull(replacement);

        using var message = new HttpRequestMessage(
            HttpMethod.Post,
            new Uri(_endpoint.BaseAddress, "api/devices/rotate"));

        message.Headers.TryAddWithoutValidation(SyncHeaders.RefreshToken, refreshToken);
        message.Headers.TryAddWithoutValidation(SyncHeaders.StoreId, _endpoint.StoreId);
        message.Headers.TryAddWithoutValidation("Accept", "application/json");
        message.Content = JsonContent.Create(
            new DeviceRotateRequest(replacement.Secret, replacement.RefreshToken),
            options: Json);

        using var response = await _http.SendAsync(message, ct).ConfigureAwait(false);
        await SyncHttpResponse.EnsureSuccessAsync(response, ct).ConfigureAwait(false);

        var result = await response.Content
            .ReadFromJsonAsync<DeviceRotateResponse>(Json, ct)
            .ConfigureAwait(false);

        return result ?? throw new HttpRequestException("The hub returned an empty rotation response.");
    }
}
